[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_20']

[phases.build]
cmds = [
  "composer install",
  "php artisan config:cache",
  "npm install",
  "npm run build",
  "chmod -R 775 storage bootstrap/cache"
]

[phases.start]
cmd = "php artisan serve --host 0.0.0.0 --port $PORT"
